[package]
name = "kailua-client"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
bytemuck.workspace = true
clap.workspace = true
lru.workspace = true

kailua-build.workspace = true
kailua-common.workspace = true

kona-client.workspace = true
kona-common.workspace = true
kona-derive.workspace = true
kona-executor.workspace = true
kona-host.workspace = true
kona-preimage.workspace = true
kona-primitives.workspace = true

risc0-zkvm.workspace = true

serde.workspace = true
spin.workspace = true
tracing.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
