[package]
name = "kailua-common"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-eips.workspace = true
alloy-primitives.workspace = true
anyhow.workspace = true
async-trait.workspace = true
bytemuck.workspace = true
c-kzg.workspace = true
lazy_static.workspace = true
lru.workspace = true
revm.workspace = true
spin.workspace = true

kona-client.workspace = true
kona-common.workspace = true
kona-common-proc.workspace = true
kona-derive.workspace = true
kona-executor.workspace = true
kona-mpt.workspace = true
kona-preimage.workspace = true
kona-primitives.workspace = true

risc0-zkvm.workspace = true
risc0-zkvm-platform.workspace = true
serde.workspace = true
